title: Han Van Nguyen
logo: "/assets/img/han.jpg"
description: An Electrical and Computer Engineer
show_downloads: false
nav:
  - name: Home
    url: "/"
  - name: Resume
    url: "/resume/"
  - name: Projects
    url: "/projects/"
  - name: Publications
    url: "/publications/"
google_analytics:
theme: jekyll-theme-minimal
plugins:
  - jekyll-seo-tag