title: Han Van Nguyen
logo: assets/images/han.jpg
description: Electrical and computer engineer
author: Han Van Nguyen
email: han.van.nguyen@gmail.com
social:
  twitter: hanvannguyen
  github: hanvannguyen
  linkedin: hanvannguyen
  facebook: hanvannguyen
  instagram: hanvannguyen
  youtube: hanvannguyen
  dribbble: hanvannguyen
  behance: hanvannguyen
  pinterest: hanvannguyen
  stackoverflow: hanvannguyen
  medium: hanvannguyen
  rss: hanvanng
show_downloads: false
theme: jekyll-theme-minimal
# Optional additional metadata:
# url: "https://yourdomain.com"
# baseurl: ""